### ISSUE TITLE
Front End?

### ISSUE THREAD

**Issue by 82rules** [codeforpg/ApiPontaGrossa#3]
Gostaria de saber opiniao sobre qual stack vc's gostaria de montar o front end?
Tenho experiencia com VueJS/Angualr e estou entrando agora no React

Dependendo do tipo de UI que queremos utilizar differente opçao tem avantages/disavantages. 
Quais technicas que temos para trabalhar em nosso equipe?

**Comment by devcodeforpg** [comment]
Eu e o Rafael fazemos o Front End, estamos nos acostumando a usar AngularJS nos nossos projetos, acho que seria mais fácil pra todos.
By-> Robson Jean

**Comment by 82rules** [comment]
Tem 2 pull requests aberto, o #6 inclui tudo que o #5 tem de banco de dados mais o inicio do front end. Começamos com VueJS pq e mais facil de aprender que Angular para o UI simplis que estavamos fazendo, se quiserem ir dando uma revisa no UI podem aprovar e merge os PR e fazer um branch para utilizar 

Se precisarem de ajuda com git/PR e so mandar um slack

**Comment by 82rules** [comment]
Vou vechar esse tbm, fomos com VueJS para o front end
